module.exports = {
  xlsxPath: "./new_data.xlsx",
  outDir: "./lang",
  // lang: ["zh", "en", "hk", "kr", "ru", "es", "pt", "fa", "ja", "tr", "fr", "vi", "de"],
  clientType: "browser",
  completeLang: ["en", "de", "kr"],
  completeBaseLang: "zh",
  // clientType: "ios",
  fileType: ".js",
  // appName: 'SERVER',
  singleFile: "aboutUs.js",
  singleKeys: ["chainAddress", "telegramAccount", "telegramCommunityLink"],
  // findMissingKey: false,
  // findMissingTerm: true,
}